### PR TITLE
Allow app to load if cfg does not come from config.env file

### LINKED ISSUE #82: Enable optional environment file loading
## Problem
Currently, in order to build and run the application, a config.env file is required otherwise the application fails. The application should not fail if an env file is not found. This is not ideal if running in a production environment and env variables are injected through the system process instead of through an env file.

## Solution
Instead of requiring the application to be run with a .env file, we should instead have a solution that allows the application to run with or without an env file present. This may mean simply logging a warning instead of failing out of the application upon not loading in an env file, or something more complex.

### PR DESCRIPTION
**Pull request by adrain-cb**
## Fixes Issue

Fixes #82

### CODE REVIEW

**Review by epociask — COMMENTED** [review]
Can we also add functionality that allows for arbitrary config file names?

**Comment by adrain-cb** [comment]
Technically it does already, you just change the file that you pass into the function. Don't think anything further would be a useful feature addition though

**Review by epociask — APPROVED** [review]
LGTM

**Comment by cb-heimdall** [comment]
Review Error for epociask @ 2023-07-26 00:13:40 UTC
User cannot review their own commit

**Review by nadir-akhtar-coinbase — APPROVED** [review]

**Pull request merged**
