### PR TITLE
Markdown linting support

### LINKED ISSUE #96: Markdown Linting Support
## Problem 
Many of the existing repo markdown documents are riddled with typos and formatting issues. This can cause confusion for users and is nonetheless poor hygiene. Adding markdown linting will help establish a consistent formatting style for Markdown files.

## Problem Solution
* Integrated markdown linting in CI
* Make directive to run markdown linter
* Repo passing markdown linting scan

### PR DESCRIPTION
**Pull request by alessandromazza98**
Closes #96 

I add `markdownlint` support in CI with a config file `.markdownlint.json` in order to not display line length errors because I think they sometimes are necessary.

I add in the `README.md` the steps to lint md files so that there are no problems in CI.

Let me know what do you think.
Thanks

### CODE REVIEW

**Comment by adrain-cb** [comment]
Hey @alessandromazza98, thanks for the contribution! Once the failing checks pass, I'll go ahead and give this a +1

**Comment by alessandromazza98** [comment]
Now I get a golang-ci lint error but it's related to a file I did not change, which is `health.go`.

**Comment by epociask** [comment]
@alessandromazza98 I see that, for some reason the last merged PR introduced this regression which for some reason wasn't detected in CI. Nonetheless I've put another [PR](https://github.com/base-org/pessimism/pull/161) in the meantime to  fix this. Once this is merged you should be able to rebase and we'll be smooth sailing ⛵

**Comment by alessandromazza98** [comment]
Should be ok now

**Review by epociask — APPROVED** [review]
LGTM - Thank you very much 🔥

**Pull request merged**
