### PR TITLE
Fixed State Key Persistence Errors

### PR DESCRIPTION
**Pull request by epociask**
## Fixes Issue

Fixes #

### CODE REVIEW

**Review by a-drain — APPROVED** [review]
lgtm

**Comment by cb-heimdall** [comment]
Review Error for a-drain @ 2023-06-23 21:28:40 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by a-drain-cb — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for a-drain-cb @ 2023-06-23 21:30:55 UTC
User must have write permissions to review

**Review by a-drain — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for a-drain @ 2023-06-23 21:33:49 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by a-drain — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for a-drain @ 2023-06-23 21:34:47 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by a-drain — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for a-drain @ 2023-06-23 21:35:28 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by adrain-cb — APPROVED** [review]

**Pull request merged**
